version: '3.7'

services:
  medstruct-gui:
    image: putssander/medstruct-gui:0.0.1-SNAPSHOT
    container_name: medstruct-gui
    environment:
    - SPRING_PROFILES_ACTIVE=docker,h2file
    expose:
    - '8080'
    ports:
    - '8080:8080'
    networks:
    - medstruct-network
    volumes:
      - "./medstruct-gui:/data"

  medstruct-api:
    image: putssander/medstruct:2.1
    container_name: medstruct-api
    expose:
    - '8081'
    ports:
    - '8081:8081'
    networks:
    - medstruct-network
    volumes:
    - './medstruct/medstruct-application.yml:/app/application.yml'

  spacy-json-nlp-medstruct:
    image: putssander/spacy-json-nlp:all_v2
    container_name: spacy-json-nlp-medstruct
    expose:
    - '5001'
    ports:
    - '5001:5001'
    environment:
    - COREFERENCES=false
    - CONSTITUENTS=false
    networks:
    - medstruct-network

  pycontext-json-nlp-medstruct-en:
    image: maastrodocker/pycontextnlp:latest
    container_name: pycontext-json-nlp-medstruct-en
    environment:
    - MODIFIERS=/data/pycontextnlp_modifiers_en.yml
    - TARGETS=/data/pycontextnlp_tnm_targets_en.yml
    expose:
    - '5003'
    ports:
    - '5030:5003'
    networks:
    - medstruct-network
    volumes:
    - "./pycontextnlp:/data"

  pycontext-json-nlp-medstruct-nl:
    image: maastrodocker/pycontextnlp:latest
    container_name: pycontext-json-nlp-medstruct-nl
    environment:
    - MODIFIERS=/data/pycontextnlp_modifiers_nl.yml
    - TARGETS=/data/pycontextnlp_tnm_targets_nl.yml
    expose:
    - '5003'
    ports:
    - '5031:5003'
    networks:
    - medstruct-network
    volumes:
    - "./pycontextnlp:/data"

  medstruct-measurement-extractor:
    image: putssander/medstruct-measurement-extractor:2.1.0
    container_name: medstruct-measurement-extractor
    expose:
    - '5004'
    ports:
    - '5004:5004'
    environment:
    - SPRING_PROFILES_ACTIVE=rest
    - SPRING_CONFIG_LOCATION=/data/medstruct-measurement-extractor-application-nl.yml
    networks:
    - medstruct-network
    volumes:
    - "./medstruct-measurement-extractor:/data"

  medstruct-tnm-classifier:
    image: putssander/medstruct-tnm-classifier:2.2.2
    container_name: medstruct-tnm-classifier
    expose:
    - '5005'
    ports:
    - '5005:5005'
    environment:
    - SPRING_PROFILES_ACTIVE=rest
    - SPRING_CONFIG_LOCATION=/data/medstruct-tnm-classifier-application-nl.yml
    networks:
    - medstruct-network
    volumes:
    - "./medstruct-tnm-classifier:/data"

networks:
  medstruct-network:
    external: true
