version: '3.7'

services:
  pycontext-json-nlp-medstruct:
    image: maastrodocker/pycontextnlp:latest
    container_name: pycontext-json-nlp-medstruct
    environment:
    - MODIFIERS=/data/pycontextnlp_modifiers_en.yml
    - TARGETS=/data/pycontextnlp_tnm_targets_en.yml
    expose:
    - '9999'
    ports:
    - '5003:5003'
    - '9999:9999'
    networks:
    - medstruct-network
    volumes:
    - "/c/Users/marti/OneDrive/Documenten/Mijn GIT/medstruct-config:/data"   
    # entrypoint: python /app/pyConTextNLP/io/tcpService.py --port=9999

  spacy-json-nlp-medstruct:
    image: putssander/spacy-json-nlp:all_v2
    container_name: spacy-json-nlp-medstruct
    expose:
    - '5001'
    ports:
    - '5001:5001'
    environment:
    - COREFERENCES=false
    - CONSTITUENTS=false
    networks:
    - medstruct-network

  medstruct-measurement-extractor:
    image: putssander/medstruct-measurement-extractor:2.1
    container_name: medstruct-measurement-extractor
    expose:
    - '5004'
    ports:
    - '5004:5004'
    environment:
    - SPRING_PROFILES_ACTIVE=rest
    - SPRING_CONFIG_LOCATION=https://raw.githubusercontent.com/putssander/medstruct-config/BOSTON-N/medstruct-measurement-extractor-application.yml
    networks:
    - medstruct-network

  medstruct-tnm-classifier:
    image: putssander/medstruct-tnm-classifier:2.2
    container_name: medstruct-tnm-classifier
    expose:
    - '5005'
    ports:
    - '5005:5005'
    environment:
    - SPRING_PROFILES_ACTIVE=rest
    - SPRING_CONFIG_LOCATION=https://raw.githubusercontent.com/putssander/medstruct-config/BOSTON-N/medstruct-tnm-classifier-application.yml
    networks:
    - medstruct-network

  medstruct-api:
    image: putssander/medstruct:2.0
    container_name: medstruct-api
    expose:
    - '8081'
    ports:
    - '8081:8081'
    volumes:
    - './medstruct-application.yml:/app/application.yml'
    networks:
    - medstruct-network

  medstruct-gui:
    image: putssander/medstruct-gui:0.1
    container_name: medstruct-gui
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    expose:
    - '8080'
    ports:
    - '8080:8080'
    networks:
    - medstruct-network

networks:
  medstruct-network:
    external: true
