measurement-extractor:
  blacklist-pattern: "(.*)-(.*)"
  split-pattern: "x"
  code-matching-bound-to-sentence-start: true

  codes:
  - code: "loinc:21889-1" #tumor size
    unit: "cm"
    preceding-concept: "snomedct:108369006" #tumor
    quantity: "LENGTH"
    sub-quantity: "DIMENSION"
  - code: "none:lymph-node-size" #lymph node size
    unit: "cm"
    preceding-concept: "snomedct:59441001" #lymph
    quantity: "LENGTH"
    sub-quantity: "DIMENSION"

  quantity-subtypes:
  - subtype: "DISTANCE"
    regex: "afstand|gebied tussen|ruimte tussen"
    quantity: "LENGTH"
  - subtype: "LOCATION"
    regex: "bevindt zich"
    quantity: "LENGTH"
  - subtype: "DIMENSION"
    regex: "groot|diameter|afmeting|korte as"
    quantity: "LENGTH"
  - subtype: "DISPLACEMENT"
    regex: "shift"
    quantity: "LENGTH"

  ordinal-map:
    "1": "one"
    "2": "two"
    "3": "three"
    "4": "four"
    "5": "five"
    "6": "six"
    "7": "seven"
    "8": "eight"
    "9": "nine"
    "10": "ten"

  quantity.length:
    normalization-unit: "cm"
    unitMmPattern: "mm|millimetre||millimetres|millimeter"
    unitCmPattern: "cm|centimetre|centimetres|centimeter"
    unitDmPattern: "dm|decimetre|decimetres|decimeter"
    dimensionAttributePattern: "(x|by|times|at least|and)"

processor.enabled: false
restcontroller.enabled: true

server:
  port: 5004

