#simple-sectionizer:
#  regex_whitelist_required:
#    - 'chest:'
#    - 'lung and pleura:'
#    - 'mediastinum:'
#  regex_whitelist_optional:
#    - 'impression:'
#  regex_blacklist:
#    - 'comparison:'
#    - 'indication:'
#    - 'radiopharmaceutical:'
#    - 'dose:'
#    - 'technique:'
#    - 'blood glucose:'
#    - 'abdomen:'
#    - 'abdomen/pelvis:'
#    - 'pelvis:'
#    - 'musculoskeletal:'
#  report_style: 'boston'
#  enabled: true

simple-sectionizer:
  regex_whitelist_required:
    - 'thorax:'
    - 'target laesie'
    - 'target lesie'
  regex_whitelist_optional:
    - 'conclusie:'
    - 'conclusie'
  regex_blacklist:
    - 'gegevens:'
    - 'vraagstelling:'
  report_style: 'mumc'
  enabled: true

preprocessor:
  replace-abbreviations:
    "ca.": "circa"
  replace-punctuations:
    ":": ""
    "-": ","
    "linker": "linker+"
    "rechter": "rechter+"

tnm-classification:
  xlsx-result-columns:
    - 'involvedText'
    - 'presentText'
    - 'satelliteNodules'
    - 'tumors'
    - 'tumorsInDiffentLobesIpsilateral'
    - 'lymphNodes'
    - 'tnmT'
    - 'tnmN'
    - 'tnmM'

medstruct:
  lang: 'nl'
  #  xlsx:
  #    text-column: 'report'
  #    label-tnm-column: 'GOLD'
  #    label-t-column: 'GOLD'
  #    label-n-column: 'N MARTIJN'
  #    label-m-column: 'GOLD'
  xlsx:
    text-column: 'report'
    label-tnm-column:
    label-t-column: 'LABEL_T'
    label-n-column: 'LABEL_N'
    label-m-column: 'LABEL_M'

  results:
    confusion-matrix-prefix: 'confusion-matrix'
    confusion-matrix-eps: true
    output-dir: '/data/reports/output.xlsx'
    dump-json-nlp: false

spacy:
  models:
    "en": "en_core_web_sm"
    "nl": "nl_core_news_sm"
#  url: 'http://localhost:5001/token_list'
  url: 'http://spacy-json-nlp-medstruct:5001/token_list'

pycontextnlp:
  url-lang-map:
#    "en": 'http://localhost:5030/json-nlp'
#    "nl": 'http://localhost:5031/json-nlp'
    "en": 'http://pycontext-json-nlp-medstruct-en:5003/json-nlp'
    "nl": 'http://pycontext-json-nlp-medstruct-nl:5003/json-nlp'


medstruct-measurement-extractor:
#  url: 'http://localhost:5004/api/json-nlp/measurements'
  url: 'http://medstruct-measurement-extractor:5004/api/json-nlp/measurements'

medstruct-tnm-client:
  # url: 'http://localhost:5005/api/classify/tnm/lung8/jsonlp'
  # url: 'http://host.docker.internal:5005/api/classify/tnm/lung8/jsonlp'
  url: 'http://medstruct-tnm-classifier:5005/api/classify/tnm/lung8/jsonlp'
